### ISSUE TITLE
Error: Could not locate the bindings file. Tried:

### ISSUE THREAD

**Issue by inspiredtolive** [NotNinja/europa#70]
I have tried updating NVM and node but this issue remains unresolved.

```
var md = require('html-md');
md('I <em>love</em> html.md!');
```
Running this in node yields this error

```
/Users/inspiredtolive/Desktop/Apps/improved-potato-bot/node_modules/bindings/bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /Users/inspiredtolive/Desktop/Apps/improved-potato-bot/node_modules/contextify/build/contextify.node
 → /Users/inspiredtolive/Desktop/Apps/improved-potato-bot/node_modules/contextify/build/Debug/contextify.node
 → /Users/inspiredtolive/Desktop/Apps/improved-potato-bot/node_modules/contextify/build/Release/contextify.node
 → /Users/inspiredtolive/Desktop/Apps/improved-potato-bot/node_modules/contextify/out/Debug/contextify.node
 → /Users/inspiredtolive/Desktop/Apps/improved-potato-bot/node_modules/contextify/Debug/contextify.node
 → /Users/inspiredtolive/Desktop/Apps/improved-potato-bot/node_modules/contextify/out/Release/contextify.node
 → /Users/inspiredtolive/Desktop/Apps/improved-potato-bot/node_modules/contextify/Release/contextify.node
 → /Users/inspiredtolive/Desktop/Apps/improved-potato-bot/node_modules/contextify/build/default/contextify.node
 → /Users/inspiredtolive/Desktop/Apps/improved-potato-bot/node_modules/contextify/compiled/7.10.0/darwin/x64/contextify.node
    at bindings (/Users/inspiredtolive/Desktop/Apps/improved-potato-bot/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/Users/inspiredtolive/Desktop/Apps/improved-potato-bot/node_modules/contextify/lib/contextify.js:1:96)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/inspiredtolive/Desktop/Apps/improved-potato-bot/node_modules/jsdom/lib/jsdom/browser/index.js:17:21)
```

Upon further inspection, it looks like there was an installation issue with contextify.

```
Exit code: 1
Command: sh
Arguments: -c node-gyp rebuild
Directory: /Users/inspiredtolive/Desktop/Apps/improved-potato-bot/node_modules/contextify
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@7.10.0 | darwin | x64
gyp http GET https://nodejs.org/download/release/v7.10.0/node-v7.10.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v7.10.0/node-v7.10.0-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v7.10.0/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v7.10.0/SHASUMS256.txt
gyp info spawn /usr/bin/python
gyp info spawn args [ '/Users/inspiredtolive/.yarn/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/inspiredtolive/Desktop/Apps/improved-potato-bot/node_modules/contextify/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/inspiredtolive/.yarn/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/inspiredtolive/.node-gyp/7.10.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/inspiredtolive/.node-gyp/7.10.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/inspiredtolive/.yarn/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/inspiredtolive/Desktop/Apps/improved-potato-bot/node_modules/contextify',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/contextify/src/contextify.o
../src/contextify.cc:131:56: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
        Local<Object> wrapper = Nan::New(constructor)->NewInstance();
                                                       ^
/Users/inspiredtolive/.node-gyp/7.10.0/include/node/v8.h:3662:52: note: 'NewInstance' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Object> NewInstance() const);
                                                   ^
../src/contextify.cc:150:16: error: no member named 'SetAccessCheckCallbacks' in 'v8::ObjectTemplate'
        otmpl->SetAccessCheckCallbacks(GlobalPropertyNamedAccessCheck,
        ~~~~~  ^
../src/contextify.cc:182:51: warning: 'GetRealNamedProperty' is deprecated [-Wdeprecated-declarations]
        Local<Value> rv = Nan::New(ctx->sandbox)->GetRealNamedProperty(property);
                                                  ^
/Users/inspiredtolive/.node-gyp/7.10.0/include/node/v8.h:3234:30: note: 'GetRealNamedProperty' has been explicitly marked deprecated here
                Local<Value> GetRealNamedProperty(Local<String> key));
                             ^
../src/contextify.cc:209:38: warning: 'GetRealNamedProperty' is deprecated [-Wdeprecated-declarations]
        if (!Nan::New(ctx->sandbox)->GetRealNamedProperty(property).IsEmpty() ||
                                     ^
/Users/inspiredtolive/.node-gyp/7.10.0/include/node/v8.h:3234:30: note: 'GetRealNamedProperty' has been explicitly marked deprecated here
                Local<Value> GetRealNamedProperty(Local<String> key));
                             ^
../src/contextify.cc:210:42: warning: 'GetRealNamedProperty' is deprecated [-Wdeprecated-declarations]
            !Nan::New(ctx->proxyGlobal)->GetRealNamedProperty(property).IsEmpty()) {
                                         ^
/Users/inspiredtolive/.node-gyp/7.10.0/include/node/v8.h:3234:30: note: 'GetRealNamedProperty' has been explicitly marked deprecated here
                Local<Value> GetRealNamedProperty(Local<String> key));
                             ^
4 warnings and 1 error generated.
make: *** [Release/obj.target/contextify/src/contextify.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/inspiredtolive/.yarn/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/Users/inspiredtolive/.nvm/versions/node/v7.10.0/bin/node" "/Users/inspiredtolive/.yarn/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/inspiredtolive/Desktop/Apps/improved-potato-bot/node_modules/contextify
gyp ERR! node -v v7.10.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
    at ChildProcess.proc.on.code (/Users/inspiredtolive/.yarn/lib/util/child.js:107:15)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:511:12)
```

Any idea on how to fix this?

**Comment by neocotic** [comment]
Sorry for taking so so very long to address this. I finally got around to doing the massive rewrite of this library that I wanted to. It's been renamed Europa and it's totally changed.

One key change that fixes this issue is that I've split up the project into several modules. `europa` is now only for browsers (and browser bundlers - e.g. browserify, webpack) and `node-europa` is now available for Node.js. This allows all Node.js-specific dependencies to be completely separated from that for the browser version. `node-europa` also contains the node-powered CLI.

I also bumped the dependency for `jsdom` to v11. While this means that `node-europa` requires Node.js version 6 or newer to be compatible with the same requirement on `jsdom`, it means no more contextify (yay! :fireworks:) This should be better for Windows users as well, who often had issues during the installation due to the somewhat complex external dependencies for contextify.

Most of all, if you want to install for browser or Node.js, now all you need is npm:

``` bash
# For browser:
$ npm install --save europa
# For Node.js:
$ npm install --save node-europa
```

Both install quickly and have no confusing dependencies or external dependencies.

I'm closing this PR now as it's no longer valid. If you still use `html-md`, please give `node-europa` a shot and let me know how you get on.

Sorry again for the massive delay.

**Comment by inspiredtolive** [comment]
Sounds great! I'll give it a try.
